"""Business-orchestration services.

Layer 2 in the hexagonal layering: blueprints call services;
services orchestrate domain objects and infrastructure adapters
(`config`, `db`, `ipc`). **No `flask` imports here** — services
must be callable from a non-Flask context (tests, future CLI tools,
the worker process) per `docs/03-CODE-QUALITY-CHARTER.md`
§"Architectural Principles / The Layering Rule".

Charter §"Test discipline" sets the bar:
    Coverage gate: ≥ 80% line coverage on
    `web/teslausb_web/services/`

Phase 0.3 establishes the empty subpackage; service modules arrive
incrementally in Phase 5 (one per feature area, with charter-review
per file).
"""

from __future__ import annotations

from teslausb_web.services.boombox_service import (
    BoomboxConfig,
    BoomboxError,
    BoomboxFile,
    BoomboxFileError,
    BoomboxListing,
    BoomboxService,
    make_boombox_service,
)
from teslausb_web.services.boombox_service import (
    DeleteResult as BoomboxDeleteResult,
)
from teslausb_web.services.boombox_service import (
    UploadResult as BoomboxUploadResult,
)
from teslausb_web.services.chime_group_service import (
    ChimeGroup,
    ChimeGroupError,
    ChimeGroupManager,
    ChimeGroupStateError,
    GroupOperationResult,
    RandomConfig,
    make_chime_group_manager,
)
from teslausb_web.services.chime_scheduler import (
    ActiveChimeResolution,
    ChimeScheduleError,
    ChimeScheduler,
    ChimeScheduleStateError,
    DateSchedule,
    HolidaySchedule,
    RecurringSchedule,
    Schedule,
    ScheduleOperationResult,
    WeeklySchedule,
    format_last_run,
    format_schedule_display,
    make_chime_scheduler,
)
from teslausb_web.services.cloud_oauth_service import (
    AuthorizationStart,
    CloudOAuthService,
    DisconnectResult,
    OAuthConfig,
    OAuthConfigError,
    OAuthCredentials,
    OAuthError,
    RefreshResult,
    TokenRefreshError,
    make_oauth_service,
)
from teslausb_web.services.cloud_rclone_service import (
    CloudRcloneService,
    RcloneAuthError,
    RcloneConfigError,
    RcloneEntry,
    RcloneError,
    RcloneListing,
    RcloneNotInstalledError,
    RcloneRemote,
    RcloneServiceConfig,
    RcloneStats,
    RcloneTransferError,
    RcloneTransferProgress,
    RcloneTransferResult,
    RcloneVersion,
    make_rclone_service,
)
from teslausb_web.services.license_plate_service import (
    LicensePlate,
    LicensePlateConfig,
    LicensePlateError,
    LicensePlateService,
    PlateBulkOperationResult,
    PlateConfigError,
    PlateDuplicateError,
    PlateMatch,
    PlateNotFoundError,
    RedactionConfig,
    make_license_plate_service,
)
from teslausb_web.services.lock_chime_service import (
    ChimeInfo,
    DeleteResult,
    FileStorageLike,
    LockChimeAudioError,
    LockChimeFileError,
    ReencodeResult,
    ReplaceResult,
    UploadResult,
    WavValidation,
    delete_chime_file,
    list_chime_files,
    normalize_audio,
    reencode_wav_for_tesla,
    replace_lock_chime,
    save_pretrimmed_wav,
    set_active_chime,
    upload_chime_file,
    validate_tesla_wav,
)
from teslausb_web.services.mapping_queries import (
    ChartCount,
    DayRouteTrip,
    DayRow,
    DrivingStats,
    EventChartData,
    EventChartPoint,
    EventRow,
    EventTypeCount,
    FsdTimelinePoint,
    MappingQueries,
    MappingQueriesConfig,
    MappingQueryError,
    PlayableTrip,
    RouteWaypoint,
    SeverityChartPoint,
    Stats,
    TripRow,
    make_mapping_queries,
)
from teslausb_web.services.samba_service import (
    SambaCommandError,
    SambaConfigError,
    SambaConfigRenderResult,
    SambaError,
    SambaNotInstalledError,
    SambaService,
    SambaServiceConfig,
    SambaShare,
    SambaStatus,
    make_samba_service,
)
from teslausb_web.services.samba_watcher import (
    SambaWatcher,
    SambaWatcherConfig,
    SambaWatcherError,
    WatcherStatus,
    make_samba_watcher,
)
from teslausb_web.services.system_settings_service import (
    SystemSettings,
    SystemSettingsConfig,
    SystemSettingsConfigError,
    SystemSettingsService,
    SystemSettingsStateError,
    make_system_settings_service,
)
from teslausb_web.services.wifi_service import (
    ApMode,
    SavedWifiNetwork,
    WifiBinaryPaths,
    WifiCommandError,
    WifiConfig,
    WifiConfigError,
    WifiConnectionRequest,
    WifiCredentials,
    WifiError,
    WifiNetwork,
    WifiService,
    WifiStatus,
    make_wifi_service,
)
from teslausb_web.services.wrap_service import (
    ValidationResult,
    WrapError,
    WrapFileError,
    WrapInfo,
    WrapService,
    make_wrap_service,
)

__all__ = (
    "ActiveChimeResolution",
    "ApMode",
    "AuthorizationStart",
    "BoomboxConfig",
    "BoomboxDeleteResult",
    "BoomboxError",
    "BoomboxFile",
    "BoomboxFileError",
    "BoomboxListing",
    "BoomboxService",
    "BoomboxUploadResult",
    "ChartCount",
    "ChimeGroup",
    "ChimeGroupError",
    "ChimeGroupManager",
    "ChimeGroupStateError",
    "ChimeInfo",
    "ChimeScheduleError",
    "ChimeScheduleStateError",
    "ChimeScheduler",
    "CloudOAuthService",
    "CloudRcloneService",
    "DateSchedule",
    "DayRouteTrip",
    "DayRow",
    "DeleteResult",
    "DisconnectResult",
    "DrivingStats",
    "EventChartData",
    "EventChartPoint",
    "EventRow",
    "EventTypeCount",
    "FileStorageLike",
    "FsdTimelinePoint",
    "GroupOperationResult",
    "HolidaySchedule",
    "LicensePlate",
    "LicensePlateConfig",
    "LicensePlateError",
    "LicensePlateService",
    "LockChimeAudioError",
    "LockChimeFileError",
    "MappingQueries",
    "MappingQueriesConfig",
    "MappingQueryError",
    "OAuthConfig",
    "OAuthConfigError",
    "OAuthCredentials",
    "OAuthError",
    "PlateBulkOperationResult",
    "PlateConfigError",
    "PlateDuplicateError",
    "PlateMatch",
    "PlateNotFoundError",
    "PlayableTrip",
    "RandomConfig",
    "RcloneAuthError",
    "RcloneConfigError",
    "RcloneEntry",
    "RcloneError",
    "RcloneListing",
    "RcloneNotInstalledError",
    "RcloneRemote",
    "RcloneServiceConfig",
    "RcloneStats",
    "RcloneTransferError",
    "RcloneTransferProgress",
    "RcloneTransferResult",
    "RcloneVersion",
    "RecurringSchedule",
    "RedactionConfig",
    "ReencodeResult",
    "RefreshResult",
    "ReplaceResult",
    "RouteWaypoint",
    "SambaCommandError",
    "SambaConfigError",
    "SambaConfigRenderResult",
    "SambaError",
    "SambaNotInstalledError",
    "SambaService",
    "SambaServiceConfig",
    "SambaShare",
    "SambaStatus",
    "SambaWatcher",
    "SambaWatcherConfig",
    "SambaWatcherError",
    "SavedWifiNetwork",
    "Schedule",
    "ScheduleOperationResult",
    "SeverityChartPoint",
    "Stats",
    "SystemSettings",
    "SystemSettingsConfig",
    "SystemSettingsConfigError",
    "SystemSettingsService",
    "SystemSettingsStateError",
    "TokenRefreshError",
    "TripRow",
    "UploadResult",
    "ValidationResult",
    "WatcherStatus",
    "WavValidation",
    "WeeklySchedule",
    "WifiBinaryPaths",
    "WifiCommandError",
    "WifiConfig",
    "WifiConfigError",
    "WifiConnectionRequest",
    "WifiCredentials",
    "WifiError",
    "WifiNetwork",
    "WifiService",
    "WifiStatus",
    "WrapError",
    "WrapFileError",
    "WrapInfo",
    "WrapService",
    "delete_chime_file",
    "format_last_run",
    "format_schedule_display",
    "list_chime_files",
    "make_boombox_service",
    "make_chime_group_manager",
    "make_chime_scheduler",
    "make_license_plate_service",
    "make_mapping_queries",
    "make_oauth_service",
    "make_rclone_service",
    "make_samba_service",
    "make_samba_watcher",
    "make_system_settings_service",
    "make_wifi_service",
    "make_wrap_service",
    "normalize_audio",
    "reencode_wav_for_tesla",
    "replace_lock_chime",
    "save_pretrimmed_wav",
    "set_active_chime",
    "upload_chime_file",
    "validate_tesla_wav",
)
