#!/bin/bash
#
# TeslaUSB Shell Configuration Wrapper
#
# This file loads configuration from config.yaml using yq.
# DO NOT EDIT THIS FILE - edit config.yaml instead.
#
# This wrapper provides bash variables from YAML for all shell scripts.
#

# Determine the location of this script
SCRIPT_DIR_CONFIG="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Determine config.yaml location (one level up from scripts/)
if [[ "$SCRIPT_DIR_CONFIG" == */scripts ]]; then
  CONFIG_YAML="$(dirname "$SCRIPT_DIR_CONFIG")/config.yaml"
else
  # If sourced from root directory script
  CONFIG_YAML="$SCRIPT_DIR_CONFIG/config.yaml"
fi

# Verify config.yaml exists
if [ ! -f "$CONFIG_YAML" ]; then
  echo "ERROR: Configuration file not found at $CONFIG_YAML" >&2
  exit 1
fi

# Check if yq is installed
if ! command -v yq &> /dev/null; then
  echo "ERROR: yq is not installed. Run setup_usb.sh to install dependencies." >&2
  exit 1
fi

# PERFORMANCE OPTIMIZATION: Call yq ONCE and parse all values
# Previous implementation called yq 25+ times which was extremely slow
# Now we call it once and use eval to set all variables
# IMPORTANT: Values are properly quoted to prevent injection attacks
eval "$(yq -r '
  "GADGET_DIR=\"" + .installation.gadget_dir + "\"",
  "TARGET_USER=\"" + .installation.target_user + "\"",
  "MNT_DIR=\"" + .installation.mount_dir + "\"",
  "IMG_CAM_NAME=\"" + .disk_images.cam_name + "\"",
  "IMG_LIGHTSHOW_NAME=\"" + .disk_images.lightshow_name + "\"",
  "LABEL1=\"" + .disk_images.cam_label + "\"",
  "LABEL2=\"" + .disk_images.lightshow_label + "\"",
  "PART1_SIZE=\"" + .setup.part1_size + "\"",
  "PART2_SIZE=\"" + .setup.part2_size + "\"",
  "RESERVE_SIZE=\"" + .setup.reserve_size + "\"",
  "SAMBA_PASS=\"" + .network.samba_password + "\"",
  "WEB_PORT=\"" + (.network.web_port | tostring) + "\"",
  "OFFLINE_AP_ENABLED=\"" + (.offline_ap.enabled | tostring) + "\"",
  "OFFLINE_AP_INTERFACE=\"" + .offline_ap.interface + "\"",
  "OFFLINE_AP_SSID=\"" + .offline_ap.ssid + "\"",
  "OFFLINE_AP_PASSPHRASE=\"" + .offline_ap.passphrase + "\"",
  "OFFLINE_AP_CHANNEL=\"" + (.offline_ap.channel | tostring) + "\"",
  "OFFLINE_AP_IPV4_CIDR=\"" + .offline_ap.ipv4_cidr + "\"",
  "OFFLINE_AP_DHCP_START=\"" + .offline_ap.dhcp_start + "\"",
  "OFFLINE_AP_DHCP_END=\"" + .offline_ap.dhcp_end + "\"",
  "OFFLINE_AP_CHECK_INTERVAL=\"" + (.offline_ap.check_interval | tostring) + "\"",
  "OFFLINE_AP_DISCONNECT_GRACE=\"" + (.offline_ap.disconnect_grace | tostring) + "\"",
  "OFFLINE_AP_MIN_RSSI=\"" + (.offline_ap.min_rssi | tostring) + "\"",
  "OFFLINE_AP_STABLE_SECONDS=\"" + (.offline_ap.stable_seconds | tostring) + "\"",
  "OFFLINE_AP_PING_TARGET=\"" + .offline_ap.ping_target + "\"",
  "OFFLINE_AP_RETRY_SECONDS=\"" + (.offline_ap.retry_seconds | tostring) + "\"",
  "OFFLINE_AP_VIRTUAL_IF=\"" + .offline_ap.virtual_interface + "\"",
  "OFFLINE_AP_FORCE_MODE=\"" + .offline_ap.force_mode + "\"",
  "CONFIG_FILE=\"" + .system.config_file + "\"",
  "SMB_CONF=\"" + .system.samba_conf + "\""
' "$CONFIG_YAML")"

# ============================================================================
# Computed paths (don't modify these)
# ============================================================================
IMG_CAM="$GADGET_DIR/$IMG_CAM_NAME"
IMG_LIGHTSHOW="$GADGET_DIR/$IMG_LIGHTSHOW_NAME"
STATE_FILE="$GADGET_DIR/state.txt"
