#!/usr/bin/env python3
"""
TeslaUSB Configuration Wrapper

This file loads configuration from config.yaml using PyYAML.
DO NOT EDIT THIS FILE - edit config.yaml instead.

This wrapper provides Python variables from YAML for the web application.
"""

import os
import secrets
import yaml

# Determine config.yaml location (two levels up from web/)
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
CONFIG_YAML = os.path.join(os.path.dirname(os.path.dirname(SCRIPT_DIR)), 'config.yaml')

# Verify config.yaml exists
if not os.path.exists(CONFIG_YAML):
    raise FileNotFoundError(f"Configuration file not found at {CONFIG_YAML}")

# Load configuration from YAML
with open(CONFIG_YAML, 'r') as f:
    config = yaml.safe_load(f)

# ============================================================================
# Extract configuration values from YAML
# ============================================================================

# Installation & Paths
GADGET_DIR = config['installation']['gadget_dir']
TARGET_USER = config['installation']['target_user']
MNT_DIR = config['installation']['mount_dir']

# Disk Images
IMG_CAM_NAME = config['disk_images']['cam_name']
IMG_LIGHTSHOW_NAME = config['disk_images']['lightshow_name']

# Network & Security
WEB_PORT = config['network']['web_port']

# Web Application Configuration
_DEFAULT_SECRET = 'CHANGE-THIS-TO-A-RANDOM-SECRET-KEY-ON-FIRST-INSTALL'
SECRET_KEY = config['web']['secret_key']

# Auto-generate a secret key on first run if still using default
if SECRET_KEY == _DEFAULT_SECRET:
    SECRET_KEY = secrets.token_hex(32)
    print(f"Generated new SECRET_KEY. Consider saving it to config.yaml for persistence.")

# Lock Chime Configuration
LOCK_CHIME_FILENAME = config['web']['lock_chime_filename']
CHIMES_FOLDER = config['web']['chimes_folder']
MAX_LOCK_CHIME_SIZE = config['web']['max_lock_chime_size']
MAX_LOCK_CHIME_DURATION = config['web']['max_lock_chime_duration']
MIN_LOCK_CHIME_DURATION = config['web']['min_lock_chime_duration']

# Audio Trimmer Configuration
SPEED_RANGE_MIN = config['web']['speed_range_min']
SPEED_RANGE_MAX = config['web']['speed_range_max']
SPEED_STEP = config['web']['speed_step']

# Light Show Configuration
LIGHT_SHOW_FOLDER = config['web']['lightshow_folder']

# ============================================================================
# ADVANCED SETTINGS - Computed values (don't modify these)
# ============================================================================

# Read-only mount directory for present mode (computed from MNT_DIR)
RO_MNT_DIR = MNT_DIR  # Same as MNT_DIR since we use -ro and -rw suffixes

# State management
STATE_FILE = os.path.join(GADGET_DIR, "state.txt")

# USB drive configuration
USB_PARTITIONS = ("part1", "part2")
PART_LABEL_MAP = {"part1": "gadget_part1", "part2": "gadget_part2"}

# Thumbnail configuration
THUMBNAIL_CACHE_DIR = os.path.join(GADGET_DIR, "thumbnails")

# Mode display configuration
MODE_DISPLAY = {
    "present": ("USB Gadget Mode", "present"),
    "edit": ("Edit Mode", "edit"),
    "unknown": ("Unknown", "unknown"),
}

# File type configurations
VIDEO_EXTENSIONS = ('.mp4', '.avi', '.mov', '.mkv')
LIGHT_SHOW_EXTENSIONS = ('.fseq', '.mp3', '.wav')

# Tesla camera angles (6 cameras)
CAMERA_ANGLES = ('front', 'back', 'left_repeater', 'right_repeater', 'left_pillar', 'right_pillar')


def empty_camera_videos():
    """Return a new dict of camera angles with None values (no video assigned)."""
    return {cam: None for cam in CAMERA_ANGLES}


def empty_encrypted_flags():
    """Return a new dict of camera angles with False values (not encrypted)."""
    return {cam: False for cam in CAMERA_ANGLES}


# Script paths (scripts are in GADGET_DIR/scripts/)
def get_script_path(script_name):
    """Get the full path to a script in the GADGET_DIR/scripts/ directory."""
    return os.path.join(GADGET_DIR, "scripts", script_name)
